//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuCoin.Resource.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuCoin.Resource.Lang.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add As Beneficiary.
        /// </summary>
        internal static string AddAsBeneficiary {
            get {
                return ResourceManager.GetString("AddAsBeneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Beneficiary.
        /// </summary>
        internal static string AddBeneficiary {
            get {
                return ResourceManager.GetString("AddBeneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Beneficiary.
        /// </summary>
        internal static string AddNewBeneficiary {
            get {
                return ResourceManager.GetString("AddNewBeneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred.
        /// </summary>
        internal static string AnErrorOccurred {
            get {
                return ResourceManager.GetString("AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiaries.
        /// </summary>
        internal static string Beneficiaries {
            get {
                return ResourceManager.GetString("Beneficiaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary.
        /// </summary>
        internal static string Beneficiary {
            get {
                return ResourceManager.GetString("Beneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary Details.
        /// </summary>
        internal static string BeneficiaryDetails {
            get {
                return ResourceManager.GetString("BeneficiaryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary List.
        /// </summary>
        internal static string BeneficiaryList {
            get {
                return ResourceManager.GetString("BeneficiaryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary Mobile Number.
        /// </summary>
        internal static string BeneficiaryMobileNumber {
            get {
                return ResourceManager.GetString("BeneficiaryMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary Name.
        /// </summary>
        internal static string BeneficiaryName {
            get {
                return ResourceManager.GetString("BeneficiaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash in .
        /// </summary>
        internal static string CashIn {
            get {
                return ResourceManager.GetString("CashIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Out.
        /// </summary>
        internal static string CashOut {
            get {
                return ResourceManager.GetString("CashOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Successfully, ThePassword Has Been Change Successfully.
        /// </summary>
        internal static string ChangePasswordALeart {
            get {
                return ResourceManager.GetString("ChangePasswordALeart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link has been sent, please check your email to reset your password..
        /// </summary>
        internal static string ChangePasswordLink {
            get {
                return ResourceManager.GetString("ChangePasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create pin code .
        /// </summary>
        internal static string CreatePIN {
            get {
                return ResourceManager.GetString("CreatePIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PIN Code.
        /// </summary>
        internal static string CreatePINCode {
            get {
                return ResourceManager.GetString("CreatePINCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Balance.
        /// </summary>
        internal static string CurrentBalance {
            get {
                return ResourceManager.GetString("CurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Transaction .
        /// </summary>
        internal static string DigitalTransaction {
            get {
                return ResourceManager.GetString("DigitalTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t Have Account.
        /// </summary>
        internal static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Fields Please Dont Leave Empty Fields.
        /// </summary>
        internal static string EmptyFields {
            get {
                return ResourceManager.GetString("EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Don’t Leave Empty Fields Must New Password Fields Matching Conform Password Field.
        /// </summary>
        internal static string EmptyFieldsError {
            get {
                return ResourceManager.GetString("EmptyFieldsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email we&apos;ll email instructions on how to reset your password.
        /// </summary>
        internal static string EnterEmailAsk {
            get {
                return ResourceManager.GetString("EnterEmailAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter University Id.
        /// </summary>
        internal static string EnterUniversityId {
            get {
                return ResourceManager.GetString("EnterUniversityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Name.
        /// </summary>
        internal static string FamilyName {
            get {
                return ResourceManager.GetString("FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decentralized Application.
        /// </summary>
        internal static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password?.
        /// </summary>
        internal static string ForgetPassword_ {
            get {
                return ResourceManager.GetString("ForgetPassword?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you forget your password?.
        /// </summary>
        internal static string ForgetPasswordAsk {
            get {
                return ResourceManager.GetString("ForgetPasswordAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget PIN Code.
        /// </summary>
        internal static string ForgetPINCode {
            get {
                return ResourceManager.GetString("ForgetPINCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget your PIN? Click Here.
        /// </summary>
        internal static string ForgetYourPIN {
            get {
                return ResourceManager.GetString("ForgetYourPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets Start.
        /// </summary>
        internal static string LetsStart {
            get {
                return ResourceManager.GetString("LetsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        internal static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number Pos.
        /// </summary>
        internal static string MobileNumberPos {
            get {
                return ResourceManager.GetString("MobileNumberPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Beneficiary.
        /// </summary>
        internal static string NewBeneficiary {
            get {
                return ResourceManager.GetString("NewBeneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Beeficiary ,Cannot Add New Benefucuary.
        /// </summary>
        internal static string NewBenificaryError {
            get {
                return ResourceManager.GetString("NewBenificaryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Beneficiaries Found.
        /// </summary>
        internal static string NoBeneficiariesFound {
            get {
                return ResourceManager.GetString("NoBeneficiariesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong PIN Code, The Code You Entered Appears To Be Incorrect Please Try Again.
        /// </summary>
        internal static string PinCodeError {
            get {
                return ResourceManager.GetString("PinCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Your PIN Code.
        /// </summary>
        internal static string PleaseEnterPIN {
            get {
                return ResourceManager.GetString("PleaseEnterPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign up and have your special HU coins account to give up from traditional transaction and achieve your work more faster than any other way .
        /// </summary>
        internal static string PleaseSignUp {
            get {
                return ResourceManager.GetString("PleaseSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        internal static string Receiver {
            get {
                return ResourceManager.GetString("Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recharge.
        /// </summary>
        internal static string Recharge {
            get {
                return ResourceManager.GetString("Recharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recharge Number.
        /// </summary>
        internal static string RechargeNumber {
            get {
                return ResourceManager.GetString("RechargeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeration.
        /// </summary>
        internal static string Registeration {
            get {
                return ResourceManager.GetString("Registeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype Password.
        /// </summary>
        internal static string RetypePassword {
            get {
                return ResourceManager.GetString("RetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name.
        /// </summary>
        internal static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Online .
        /// </summary>
        internal static string SecondPage {
            get {
                return ResourceManager.GetString("SecondPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Beneficiary .
        /// </summary>
        internal static string SelectBeneficiary {
            get {
                return ResourceManager.GetString("SelectBeneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Prefer Language.
        /// </summary>
        internal static string SelectPreferLanguage {
            get {
                return ResourceManager.GetString("SelectPreferLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send istruction.
        /// </summary>
        internal static string SendInstruction {
            get {
                return ResourceManager.GetString("SendInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignIn.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take off the traditional money, you can make your individual transaction without bank account and any extra effort .
        /// </summary>
        internal static string ThirdPage {
            get {
                return ResourceManager.GetString("ThirdPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is found to serve many categories which they do not prefer to deal with centralized organization .
        /// </summary>
        internal static string Thisapp {
            get {
                return ResourceManager.GetString("Thisapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time .
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Beneficiary.
        /// </summary>
        internal static string ToBeneficiary {
            get {
                return ResourceManager.GetString("ToBeneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Details.
        /// </summary>
        internal static string TransactionDetails {
            get {
                return ResourceManager.GetString("TransactionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction History.
        /// </summary>
        internal static string TransactionHistory {
            get {
                return ResourceManager.GetString("TransactionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction ID.
        /// </summary>
        internal static string TransactionId {
            get {
                return ResourceManager.GetString("TransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to person .
        /// </summary>
        internal static string TransferToPerson {
            get {
                return ResourceManager.GetString("TransferToPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniversityId.
        /// </summary>
        internal static string UniversityId {
            get {
                return ResourceManager.GetString("UniversityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile, Your Profile Information Update Successfully.
        /// </summary>
        internal static string UpdateProfileAleart {
            get {
                return ResourceManager.GetString("UpdateProfileAleart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code has been  Sent to.
        /// </summary>
        internal static string VerificationCodeSent {
            get {
                return ResourceManager.GetString("VerificationCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunatley, We Were Unable To Verify Your Phone Number, Please Try Again If  Proplem Recures Please Contact Support.
        /// </summary>
        internal static string VerificationError {
            get {
                return ResourceManager.GetString("VerificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Required.
        /// </summary>
        internal static string VerificationRequired {
            get {
                return ResourceManager.GetString("VerificationRequired", resourceCulture);
            }
        }
    }
}
